logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

server:
  port: 8081

arch:
  application-id: sampleDiplomas
  event-broker-active: false
  role-mapping-default: default-roles-mufacerealm
  white-list: /expedientes, /expedientes/**, /diplomas, /diplomas/**, /organismos, /organismos/**, /actuator/health/readiness, /actuator/health/liveness, /v3/api-docs/**


spring:
  mandatory-file-encoding: UTF-8
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/mufacerealm
          jwk-set-uri: http://localhost:8080/realms/mufacerealm/protocol/openid-connect/certs

  # diplomas bbdd
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
    initialize: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.H2Dialect

  # clientes bbdd
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/bdSample
      database: bdSample

  # Event bus configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

auditoria:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/auditDB
      database: auditDB

    sql:
      init:
        mode: always
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
      properties:
        hibernate:
          format_sql: true
